add basic multiarch support to resulting package and executable locations
Focusing mostly on the shipped location of some build artefacts and
the path used to execute them, most other stuff should be somewhat OK
already due to our my client build for the arch linux user repo  that
was also tested on arm64 and some community effort to build
client/server for arm64 already.

Nothing really tested, amd64/x86_64 should work as well as it did
before, additionally we should be now prepared for arm64 and riscv64,
but again, those are not really fully tested yet, there may be
dragons.

Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/debian/proxmox-backup-file-restore.postinst b/debian/proxmox-backup-file-restore.postinst
--- a/debian/proxmox-backup-file-restore.postinst
+++ b/debian/proxmox-backup-file-restore.postinst
@@ -3,8 +3,20 @@
 set -e
 
 update_initramfs() {
+
+    ARCH="${DPKG_MAINTSCRIPT_ARCH:-$(dpkg --print-architecture)}"
+    case "$ARCH" in
+        amd64) HOST_MULTIARCH="x86_64-linux-gnu" ;;
+        arm64) HOST_MULTIARCH="aarch64-linux-gnu" ;;
+        riscv64) HOST_MULTIARCH="riscv64-linux-gnu" ;;
+        *)
+            echo "Error: Unsupported architecture '$ARCH', amd64, arm64, and riscv64 are supported." >&2
+            exit 1
+            ;;
+    esac
+
     # regenerate initramfs for single file restore VM
-    INST_PATH="/usr/lib/x86_64-linux-gnu/proxmox-backup/file-restore"
+    INST_PATH="/usr/lib/${HOST_MULTIARCH}/proxmox-backup/file-restore"
     CACHE_PATH="/var/cache/proxmox-backup/file-restore-initramfs.img"
     CACHE_PATH_DBG="/var/cache/proxmox-backup/file-restore-initramfs-debug.img"
 
